name: release

on:
  schedule:
    - cron: '6 5 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements.txt'
      - run: pip install --upgrade pip wheel setuptools
      - run: pip install -r scripts/requirements.txt
      - run: poetry config virtualenvs.create false
      - run: bash scripts/find-new-version-and-release.sh
      - name: check packages
        id: check_packages
        uses: andstor/file-existence-action@v2
        with:
          files: "dist/*.whl"
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.check_packages.outputs.files_exists == 'true'
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
