name: release

on:
  schedule:
    - cron: '37 * * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip wheel setuptools
      - run: pip install -r scripts/requirements.txt
      - run: bash scripts/find-new-version-and-release.sh
      - uses: pypa/gh-action-pypi-publish@master
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist
